name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build: 
    # Name the Job
    name: Build the Pi Image
    # Set the type of machine to run on
    runs-on: ubuntu-16.04

    steps:

      # Checkout code.
      - uses: actions/checkout@v1
        
      - name: Add Elbe Debian Repository
        uses: myci-actions/add-deb-repo@4
        with:
          repo: deb http://debian.linutronix.de/elbe buster main
          repo-name: elbe
          update: false

      - name: Add Elbe Common Debian Repository
        uses: myci-actions/add-deb-repo@4
        with:
          repo: http://debian.linutronix.de/elbe-common buster main
          repo-name: elbe common
          update: false

      - name: Elbe Install With Keys
        run: | 
          sudo wget -q -O - http://debian.linutronix.de/elbe-common/elbe-repo.pub | sudo apt-key add - 
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553
          sudo apt-get update 
          sudo apt-get install elbe 
          sudo apt-get install libvirt-daemon-system
        
      - name: Let in all the leet haxors
        run: | 
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DCC9EFBF77E11517

      - name: Elbe InitVM
        run: | 
          MY_USERID=$(whoami) 
          sudo adduser $MY_USERID libvirt 
          sudo adduser $MY_USERID libvirt-qemu 
          mkdir build 
          cd build 
          sudo elbe initvm create 
